### ISSUE TITLE
Parallel

### ISSUE THREAD

**Issue by otajor** [a-la-node/hapi-project#55]
https://github.com/a-la-node/hapi-project/blob/master/src/identity.js#L43

Nice solution to this problem with your parallel function :) is there a reason why you're calling your callback with undefined in the error spot instead of null as in other functions? Not a big deal as they're both falsy but might as well be consistent.

For future reference, promises would be the other way to solve this problem, maybe [Bluebird.props](http://bluebirdjs.com/docs/api/promise.props.html) if you wanted the results in a nice object:
```javascript
function getIdentity(type){
  return Promise.props({
    newName: getNewName(),
    newPlace: getNewPlace(type)
  })
}

getIdentity('witness').then(console.log) // { newName: 'someName', newPlace: 'somePlace' }
```
Not sure if you're meant to be using promises yet though!

**Comment by Cleop** [comment]
I think promises is coming in a future week. I can change undefined to null though. I think we used undefined as we were using a past exercise of parallel which had it written this way but I agree null would be more consistent!

**Comment by otajor** [comment]
Nice, closing
