### ISSUE TITLE
register called twice

### ISSUE THREAD

**Issue by otajor** [a-la-node/hapi-project#56]
https://github.com/a-la-node/hapi-project/blob/master/src/server.js#L53

I don't think you need to be calling `server.register` twice with the different plugins you're using - is there a reason you're doing it like this?

I think this would work just as well: 

```javascript
server.register([Vision, Inert], err => {
  // ... do all the stuff here


```

**Comment by Jbarget** [comment]
also nothing is being done with the `err` in this case so it will just be failing 'silently' if there is a problem
