### ISSUE TITLE
Can export your server.start out of server.js

### ISSUE THREAD

**Issue by Jbarget** [a-la-node/hapi-project#61]
https://github.com/a-la-node/hapi-project/blob/master/src/server.js#L69-L72

so that when you're testing your back-end code by requiring in `server.js` your server wont be started and you wont need to do `server.stop()`

https://github.com/a-la-node/hapi-project/blob/master/tests/server.test.js#L11

**Comment by Jbarget** [comment]
eg. https://github.com/FAC9/hapi-places/blob/master/src/starter.js

**Comment by skibinska** [comment]
link to pull request: https://github.com/a-la-node/hapi-project/pull/72

**Comment by Jbarget** [comment]
👍  nice one
