### ISSUE TITLE
Use of let vs const

### ISSUE THREAD

**Issue by msmichellegar** [a-la-node/hapi-project#73]
Some variables declared using `let` make more sense as `const`. For instance, [here](https://github.com/a-la-node/hapi-project/blob/master/src/identity.js#L9-L14):

```js
if (!error && response.statusCode === 200) {
      let name = JSON.parse(body).results[0].name;
      let firstName = capitalise(name.first);
      let lastName = capitalise(name.last);
      return cb(null, `${firstName} ${lastName}`);
}
```

In this example, you are not reassigning any of those three variables, so may as well use `const`. It won't break your code to leave it as is, but would be better practice to change.

**Comment by skibinska** [comment]
link to pull request: https://github.com/a-la-node/hapi-project/pull/74
